[project]
name = "traditional-ml-concepts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "catboost>=1.2.10",
    "imbalanced-learn>=0.14.2",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "joblib>=1.5.3",
    "jupyter>=1.1.1",
    "lightgbm>=4.6.0",
    "matplotlib>=3.11.0",
    "notebook>=7.6.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "plotly>=6.8.0",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
    "streamlit>=1.65.0",
    "tqdm>=4.68.4",
    "xgboost>=3.3.0",
]
